### ISSUE TITLE
Requirements Specification Writeup

### ISSUE THREAD

**Issue by AoMedium** [junqi108/Functional-structural-plant-model-prototype#4]
**Start date:** 21 Nov
**Duration:** 2 weeks

**Description:** Requirements specification writeup after elicitation rounds.

**Subtasks:**
- [x] Elicitation round 1 (21 Nov)
- [x] Update requirements for input and output after 22 Nov meeting
- [x] Familiarisation with .rgg and XCompiler Java specific nuances

- [x] Elicitation round 2 (?)
- [x] Writeup (Config and DataStore)

**Comment by AoMedium** [comment]
Finished 6 Dec 2022
